version: '3'
services:
  web:
    build: .
    command: [sh, -c, npm install && npm start]
    env_file: .env
    volumes:
      - .:/myapp
    links:
      - "redis"
    ports:
      - "3000:3000"
      - "8080:8080"
    tty: true

  redis:
    image: redis:4.0
    command: redis-server --appendonly yes
    volumes:
      - ./redis:/data
    tty: true